### ISSUE TITLE
setup my license in the container when starting

### ISSUE THREAD

**Issue by casertap** [dlsniper/docker-intellij#3]
Hi, I have a personal license of intellij and I would like to set the license inside of the container ones and for all.
Either by rebuilding a new image and put the license at the right location. or has a volume at runtime.

Is this possible?
Thanks, awesome work!

**Comment by dlsniper** [comment]
Hi, sorry for the delayed work.
Unfortunately I cannot help you with this.
Please ask the JetBrains Support team to help you out with this. If they can help out, it would be interesting if you could either send a PR or open an issue with the delays and I can pick it up later on.
Thank you for your interest and sorry I don't have a better answer for you.
